spring:
  application:
    name: ApiGateway
  output:
    ansi:
      enabled: ALWAYS

  config:
    import: "configserver:http://localhost:8085"
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

server:
  port: 8084
