spring:
  application:
    name: HotelService
  config:
    import: "configserver:http://localhost:8085"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8082


# debug: true

