spring:
  application:
    name: ConfigServer
  output:
    ansi:
      enabled: ALWAYS

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nikhilkothare2106/hotel-rating-microservice-config
          clone-on-start: true
server:
  port: 8085