spring:
  application:
    name: ServiceRegistry
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
