spring:
  application:
    name: UserService
  config:
    import: "configserver:http://localhost:8085"
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri:
      database: microservice-user

server:
  port: 8081

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

retry:
  instance:
    ratingHotelService:
      max-attemps: 3
      wait-duration: 5s

resilience4j.ratelimiter:
  instances:
    userRateLimiter:
      limit-refresh-period: 10s
      limit-for-period: 2
      timeout-duration: 0
# logging:
#   level:
#     org.springframework.data.mongodb.core: DEBUG

# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka
#   instance:
#     prefer-ip-address: true

