spring:
  application:
    name: UserService
  config:
    import: "configserver:http://localhost:8085"
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri:
      database: microservice-user

server:
  port: 8081
# logging:
#   level:
#     org.springframework.data.mongodb.core: DEBUG

# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka
#   instance:
#     prefer-ip-address: true

