spring:
  application:
    name: RatingService
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: 
      database: microservice-rating

server:
  port: 8083

# logging:
#   level:
#     org.springframework.data.mongodb.core: DEBUG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
