spring:
  application:
    name: RatingService
  config:
    import: "configserver:http://localhost:8085"
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri:
      database: microservice-rating

server:
  port: 8083
# logging:
#   level:
#     org.springframework.data.mongodb.core: DEBUG
