spring:
  application:
    name: RatingService
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8085}
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: ${MONGO_URI}

server:
  port: ${SERVER_PORT:8083}
# logging:
#   level:
#     org.springframework.data.mongodb.core: DEBUG
